# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "debian/stretch64"
    
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 4
  end

  # RabbitMQ ports
  config.vm.network "forwarded_port", guest: 15672, host: 15672
  config.vm.network "forwarded_port", guest: 5672, host: 5672
  # Erlang and inet_dist_listen_min/max cluster ports - probably not needed for normal dev operation
  config.vm.network "forwarded_port", guest: 4369, host: 4369
  config.vm.network "forwarded_port", guest: 35197, host: 35197

end
