# Default application.yml

server:
  port: 8079

resourcesharing:
  rabbit:
    hostname: localhost
    username: rsms
    password: rsms

logging:
  level:
    root: WARN
    org.springframework.web: ERROR
    com.howtodoinjava: DEBUG
    org.hibernate: ERROR
    org.olf: DEBUG
    com.k_int: DEBUG

