wibble: 'This is a test value'

resourcesharing:
  rabbit:
    hostname: rabbitmq
    username: adm
    password: admpass

# server:
#     port: 8083

logging:
  level:
    root: WARN
    org.springframework.web: ERROR
    com.howtodoinjava: DEBUG
    org.hibernate: ERROR
    org.olf: DEBUG
    com.k_int: DEBUG
